import type { Metadata } from "next";
// import localFont from "next/font/local";


import './globals.css';  
import { Roboto, Poppins } from "next/font/google";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });



const roboto = Roboto({
  weight: '400', // Regular
  subsets: ['latin'], // Choose the required subset
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TravelersClan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    {/* Apply Poppins font to the entire app */}
    <body className={`${roboto.className} ${poppins.className}`}>
      {children}
    </body>
  </html>
  );
}
